/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  App as HabApp
} from './components/hab-app/hab-app';

declare global {
  interface HTMLHabAppElement extends HabApp, HTMLElement {
  }
  var HTMLHabAppElement: {
    prototype: HTMLHabAppElement;
    new (): HTMLHabAppElement;
  };
  interface HTMLElementTagNameMap {
    "hab-app": HTMLHabAppElement;
  }
  interface ElementTagNameMap {
    "hab-app": HTMLHabAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "hab-app": JSXElements.HabAppAttributes;
    }
  }
  namespace JSXElements {
    export interface HabAppAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AppProfile as HabTest
} from './components/hab-test/hab-test';

declare global {
  interface HTMLHabTestElement extends HabTest, HTMLElement {
  }
  var HTMLHabTestElement: {
    prototype: HTMLHabTestElement;
    new (): HTMLHabTestElement;
  };
  interface HTMLElementTagNameMap {
    "hab-test": HTMLHabTestElement;
  }
  interface ElementTagNameMap {
    "hab-test": HTMLHabTestElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "hab-test": JSXElements.HabTestAttributes;
    }
  }
  namespace JSXElements {
    export interface HabTestAttributes extends HTMLAttributes {
      
    }
  }
}

