/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  AppProfile as HabTest
} from './components/hab-test/hab-test';

declare global {
  interface HTMLHabTestElement extends HabTest, HTMLStencilElement {
  }
  var HTMLHabTestElement: {
    prototype: HTMLHabTestElement;
    new (): HTMLHabTestElement;
  };
  interface HTMLElementTagNameMap {
    "hab-test": HTMLHabTestElement;
  }
  interface ElementTagNameMap {
    "hab-test": HTMLHabTestElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "hab-test": JSXElements.HabTestAttributes;
    }
  }
  namespace JSXElements {
    export interface HabTestAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
