/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  habAccordion as HabAccordion
} from './components/hab-accordion/hab-accordion';

declare global {
  interface HTMLHabAccordionElement extends HabAccordion, HTMLStencilElement {
  }
  var HTMLHabAccordionElement: {
    prototype: HTMLHabAccordionElement;
    new (): HTMLHabAccordionElement;
  };
  interface HTMLElementTagNameMap {
    "hab-accordion": HTMLHabAccordionElement;
  }
  interface ElementTagNameMap {
    "hab-accordion": HTMLHabAccordionElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "hab-accordion": JSXElements.HabAccordionAttributes;
    }
  }
  namespace JSXElements {
    export interface HabAccordionAttributes extends HTMLAttributes {
      name?: string;
    }
  }
}


import {
  habDropdown as HabDropdown
} from './components/hab-dropdown/hab-dropdown';

declare global {
  interface HTMLHabDropdownElement extends HabDropdown, HTMLStencilElement {
  }
  var HTMLHabDropdownElement: {
    prototype: HTMLHabDropdownElement;
    new (): HTMLHabDropdownElement;
  };
  interface HTMLElementTagNameMap {
    "hab-dropdown": HTMLHabDropdownElement;
  }
  interface ElementTagNameMap {
    "hab-dropdown": HTMLHabDropdownElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "hab-dropdown": JSXElements.HabDropdownAttributes;
    }
  }
  namespace JSXElements {
    export interface HabDropdownAttributes extends HTMLAttributes {
      item?: any;
      name?: string;
    }
  }
}


import {
  AppProfile as HabTest
} from './components/hab-test/hab-test';

declare global {
  interface HTMLHabTestElement extends HabTest, HTMLStencilElement {
  }
  var HTMLHabTestElement: {
    prototype: HTMLHabTestElement;
    new (): HTMLHabTestElement;
  };
  interface HTMLElementTagNameMap {
    "hab-test": HTMLHabTestElement;
  }
  interface ElementTagNameMap {
    "hab-test": HTMLHabTestElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "hab-test": JSXElements.HabTestAttributes;
    }
  }
  namespace JSXElements {
    export interface HabTestAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
